"""add phone number

Revision ID: dbcce83cedfa
Revises: 1e8e7e125561
Create Date: 2022-08-27 19:41:24.297994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dbcce83cedfa'
down_revision = '1e8e7e125561'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.drop_column('users', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
